### PR TITLE
Initial RFC for publishConfig for yarn

### PR DESCRIPTION
**Pull request by DarthHater**
This is an initial draft for adding the ability to use publishConfig with yarn.

@bestander this is functionality that I think would be very useful for use with Nexus Repository Manager, Artifactory, etc...

### CODE REVIEW

**Comment by ljharb** [comment]
+1, this would be great. publishConfig is an important safety measure that npm respects, and it would be potentially very disastrous to run `yarn publish` in a previously npm-managed package, and accidentally make a private package irrevocably public.

**Comment by DarthHater** [comment]
@ljharb I think there are currently measures to prevent that, yarn seems to pick up the private variable, so those would get shortcut, IF you have that set.

**Comment by ljharb** [comment]
Correct, but that's a big "if". Often publishConfig is the only mechanism - and that was sufficient with npm.

**Comment by bestander** [comment]
Considering that this feature is already in npm I agree, this should be implemented in Yarn.
FYI, we are planning to work big on publish command in the next 3-4 months to bring some [lerna](https://github.com/lerna/lerna) features

**Comment by DarthHater** [comment]
@bestander this would be cool to add in the short term, I think it would be very useful for users using a private registry. I've got a branch where I'm working on the implementation, pending approval over here.

**Comment by Daniel15** [comment]
Nice! I didn't know about publishConfig. I agree with this 😃 

This is somewhat related to https://github.com/yarnpkg/yarn/issues/547, where I mentioned that we should have better handling for custom npm servers.

**Comment by bestander** [comment]
@DarthHater, looks like no one objects and this seems like a very important feature.
Please send the PR when you have a chance :)

**Pull request merged**
