### PR TITLE
Support per-dependency target environments & record them in `package.json` file & `yarn` cli;

### PR DESCRIPTION
**Pull request by hulkish**

### CODE REVIEW

**Comment by hulkish** [comment]
https://github.com/yarnpkg/rfcs/issues/46

**Comment by hulkish** [comment]
?

**Comment by doug-wade** [comment]
@hulkish this breaks interop with npm, and is unlikely to get merged.  Maybe #36 would work for your use case instead?

**Comment by bestander** [comment]
What are you trying to achieve?
Speed of installation?
Categorization to make package.json more readable for developers?

Would be nice to see some real world example with the problem and how it is being managed right now

**Comment by hulkish** [comment]
@bestander Well,  tooling aside I think it'd be helpful to know the nature of use for each included dependency. Simply "dev"  "peer" or "normal"  dependencies dont account for this.

**Comment by bestander** [comment]
I don't really have a strong opinion on this.
It sounds like it can be convenient to categorize large dependency lists but it does not seem to be helping much for very large package.json files anyway.

**Comment by hulkish** [comment]
close this... i guess?

**Pull request closed without merging**
