### PR TITLE
auto-build-rfc

### PR DESCRIPTION
**Pull request by hemanth**
//cc @samccone @kittens 

#11

### CODE REVIEW

**Comment by ljharb** [comment]
@hemanth if you want a postinstall script, couldn't you add one under "postinstall"?

**Comment by hemanth** [comment]
Yes, that's what I meant in [yarn#1416](https://github.com/yarnpkg/yarn/issues/1416).

**Comment by Daniel15** [comment]
Do any other packages automatically build when you run `npm install`? That feels a bit too magical for me 😛 

What is the purpose of this change?

**Comment by hemanth** [comment]
For making things easier with `git clone` and `npm link`.

**Comment by Daniel15** [comment]
Sure, but what's the end goal? 😃 

For a user of Yarn that wants to use the latest version, we have nightly builds available to use (https://yarnpkg.com/en/docs/nightly)
For someone building on Yarn itself, you'd need to know how to build Yarn, so I'm not sure that automating just the first build will actually help, unless people end up understanding exactly why it happens. 

I'm not against the change at all, just curious as to its motivation.

**Comment by hemanth** [comment]
> I'm not against the change at all, just curious as to its motivation.

Laziness being the main motivation ;) 

On a serious not, say someone is making a PR to yarn repo, if `npm link` does the required, it would be one step lesser and easier?

**Comment by Daniel15** [comment]
> say someone is making a PR to yarn repo, if npm link does the required, it would be one step lesser and easier?

For what it's worth, I don't use `npm link` when building on Yarn. I just run it with the exact absolute path (for example, `c:\src\yarn\bin\yarn` or `/usr/local/src/yarn/bin/yarn`). It makes it immediately obvious exactly *which* version of Yarn I'm running :)

**Comment by doug-wade** [comment]
@hemanth why aren't we proposing use of the [npm `prepare` script](https://github.com/npm/npm/releases/tag/v4.0.0) for this?  It seems to me that following the npm pattern would be better for interoperability, and make this easier.

**Comment by bestander** [comment]
done via https://github.com/yarnpkg/yarn/pull/3553

**Pull request closed without merging**
