### PR TITLE
add alias system

### PR DESCRIPTION
**Pull request by voxsim**
After digging in many issues of the yarn project, I think we should do something like this!

Let me know if you like the idea ;)

### CODE REVIEW

**Comment by bestander** [comment]
Not a huge fan, I think modern shell interpreters can fill this niche without any change needed in Yarn.

**Comment by gsklee** [comment]
This can be done in shell fairly easily: http://stackoverflow.com/questions/7131670/make-a-bash-alias-that-takes-a-parameter

**Comment by voxsim** [comment]
Yep I know, but before closing this pr, I think we should decide some things:
- We now have a bunch of unsopported aliases, maybe we should delete that part (https://github.com/yarnpkg/yarn/blob/master/src/cli/unsupported-aliases.js) because it gives confusion in some way
- We sometime use ls, rm for some commands, maybe we should use always the long version and deprecate the short one. This is always for consistency.
- We should close all the issue related to alias something and tell everyone that we don't want to support this and I am ok with that, I can do without any problems :)

Let me know what you think ;)

**Comment by gsklee** [comment]
Yeah, basically what we need is some valiant soul willing to do the triage works to clean things up a bit :p

**Comment by bestander** [comment]
Ho ho ho, a new triage session is going to start!

**Comment by bestander** [comment]
I've the next 2 weeks for issue triaging, this task is there for coordination https://github.com/yarnpkg/yarn/issues/3474.

The goal is to get ALL issues under control, prioritize and fix the ones critical for 1.0 release.

**Comment by bestander** [comment]
Back to this PR, I vote to remove the aliases and educate people to create their own aliases for their workflows

**Comment by gsklee** [comment]
Probably also wanna add a list of popular feature requests that have been discussed thoroughly and rejected into the issue template of either the main repo or this one.

**Comment by bestander** [comment]
As for education, anyone, send a blog post entry here https://github.com/yarnpkg/website/tree/master/_posts how people can add aliases for their favorite operating system using Yarn

**Comment by gsklee** [comment]
@bestander Finally got the time... once the blog post is accepted this RFC can be resolved I believe.

**Pull request closed without merging**
