### PR TITLE
Global Flat Linked Package Folder with no bloating node_modules in each project 

### PR DESCRIPTION
**Pull request by vairamsvsjdo**
Global Flat Linked Package Folder with no bloating node_modules in each project.

### CODE REVIEW

**Comment by bestander** [comment]
This is how Yarn was intended to work originally but this did not work for Node.js because too many modules depend on the physical structure of folders.
For more info see this discussion https://github.com/yarnpkg/yarn/blob/master/__tests__/commands/install/integration.js#L306

**Comment by bestander** [comment]
At this stage - we are not ready to get this feature in.
As discussed quite a few times there are many CONs to this approach.
But I would suggest this - let's make the `linking` phase of installation, when files are copied from cache to node_modules, pluggable.
So that users could implement their own strategies for linking, then global symlinking could be one of them.

**Comment by vairamsvsjdo** [comment]
What are other benefits of yarn over npm?

**Comment by vairamsvsjdo** [comment]
How does yarn will achieve caching if dependencies are nested.
Will it download dependencies twice or it copies flat and adds to the nest?

**Comment by pauldraper** [comment]
See #2125

**Pull request closed without merging**
